services:
  web:
    build: .
    image: vjay123/myflaskapp:latest
    ports:
      - "9000:5000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
